version: "3.8"
services:
  chat-api:
    image: trannamtrung1st/min-chat-net:chat-api-1.0
    ports:
      - target: 80
        published: 8080
    depends_on:
      - postgres
      - cass1

  chat-client:
    image: trannamtrung1st/min-chat-net:chat-client-1.0
    ports:
      - target: 80
        published: 7070

  postgres:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123456
      
  cass1:
    image: trannamtrung1st/min-chat-net:mcn-cass-1.0
    ports:
      - 9042:9042
    restart: always

networks:
  default:
    name: min-chat-net-network
